/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface ILendingPoolContract
  extends Truffle.Contract<ILendingPoolInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<ILendingPoolInstance>;
}

export interface Borrow {
  name: "Borrow";
  args: {
    _reserve: string;
    _user: string;
    _amount: BN;
    _borrowRateMode: BN;
    _borrowRate: BN;
    _originationFee: BN;
    _borrowBalanceIncrease: BN;
    _referral: BN;
    _timestamp: BN;
    0: string;
    1: string;
    2: BN;
    3: BN;
    4: BN;
    5: BN;
    6: BN;
    7: BN;
    8: BN;
  };
}

export interface Deposit {
  name: "Deposit";
  args: {
    _reserve: string;
    _user: string;
    _amount: BN;
    _referral: BN;
    _timestamp: BN;
    0: string;
    1: string;
    2: BN;
    3: BN;
    4: BN;
  };
}

export interface LiquidationCall {
  name: "LiquidationCall";
  args: {
    _collateral: string;
    _reserve: string;
    _user: string;
    _purchaseAmount: BN;
    _liquidatedCollateralAmount: BN;
    _accruedBorrowInterest: BN;
    _liquidator: string;
    _receiveAToken: boolean;
    _timestamp: BN;
    0: string;
    1: string;
    2: string;
    3: BN;
    4: BN;
    5: BN;
    6: string;
    7: boolean;
    8: BN;
  };
}

export interface OriginationFeeLiquidated {
  name: "OriginationFeeLiquidated";
  args: {
    _collateral: string;
    _reserve: string;
    _user: string;
    _feeLiquidated: BN;
    _liquidatedCollateralForFee: BN;
    _timestamp: BN;
    0: string;
    1: string;
    2: string;
    3: BN;
    4: BN;
    5: BN;
  };
}

export interface RebalanceStableBorrowRate {
  name: "RebalanceStableBorrowRate";
  args: {
    _reserve: string;
    _user: string;
    _newStableRate: BN;
    _borrowBalanceIncrease: BN;
    _timestamp: BN;
    0: string;
    1: string;
    2: BN;
    3: BN;
    4: BN;
  };
}

export interface RedeemUnderlying {
  name: "RedeemUnderlying";
  args: {
    _reserve: string;
    _user: string;
    _amount: BN;
    _timestamp: BN;
    0: string;
    1: string;
    2: BN;
    3: BN;
  };
}

export interface Repay {
  name: "Repay";
  args: {
    _reserve: string;
    _user: string;
    _repayer: string;
    _amountMinusFees: BN;
    _fees: BN;
    _borrowBalanceIncrease: BN;
    _timestamp: BN;
    0: string;
    1: string;
    2: string;
    3: BN;
    4: BN;
    5: BN;
    6: BN;
  };
}

export interface ReserveUsedAsCollateralDisabled {
  name: "ReserveUsedAsCollateralDisabled";
  args: {
    _reserve: string;
    _user: string;
    0: string;
    1: string;
  };
}

export interface ReserveUsedAsCollateralEnabled {
  name: "ReserveUsedAsCollateralEnabled";
  args: {
    _reserve: string;
    _user: string;
    0: string;
    1: string;
  };
}

export interface Swap {
  name: "Swap";
  args: {
    _reserve: string;
    _user: string;
    _newRateMode: BN;
    _newRate: BN;
    _borrowBalanceIncrease: BN;
    _timestamp: BN;
    0: string;
    1: string;
    2: BN;
    3: BN;
    4: BN;
    5: BN;
  };
}

type AllEvents =
  | Borrow
  | Deposit
  | LiquidationCall
  | OriginationFeeLiquidated
  | RebalanceStableBorrowRate
  | RedeemUnderlying
  | Repay
  | ReserveUsedAsCollateralDisabled
  | ReserveUsedAsCollateralEnabled
  | Swap;

export interface ILendingPoolInstance extends Truffle.ContractInstance {
  /**
   * deposits The underlying asset into the reserve. A corresponding amount of the overlying asset (aTokens) is minted.
   * @param _amount the amount to be deposited
   * @param _referralCode integrators are assigned a referral code and can potentially receive rewards.*
   * @param _reserve the address of the reserve
   */
  deposit: {
    (
      _reserve: string,
      _amount: number | BN | string,
      _referralCode: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _reserve: string,
      _amount: number | BN | string,
      _referralCode: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _reserve: string,
      _amount: number | BN | string,
      _referralCode: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _reserve: string,
      _amount: number | BN | string,
      _referralCode: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * accessory functions to fetch data from the core contract*
   */
  getReserveData(
    _reserve: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<[BN, BN, BN, BN, BN, BN, BN, BN, BN, BN, BN, string, BN]>;

  getReserves(txDetails?: Truffle.TransactionDetails): Promise<string[]>;

  methods: {
    /**
     * deposits The underlying asset into the reserve. A corresponding amount of the overlying asset (aTokens) is minted.
     * @param _amount the amount to be deposited
     * @param _referralCode integrators are assigned a referral code and can potentially receive rewards.*
     * @param _reserve the address of the reserve
     */
    deposit: {
      (
        _reserve: string,
        _amount: number | BN | string,
        _referralCode: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _reserve: string,
        _amount: number | BN | string,
        _referralCode: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _reserve: string,
        _amount: number | BN | string,
        _referralCode: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _reserve: string,
        _amount: number | BN | string,
        _referralCode: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * accessory functions to fetch data from the core contract*
     */
    getReserveData(
      _reserve: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<[BN, BN, BN, BN, BN, BN, BN, BN, BN, BN, BN, string, BN]>;

    getReserves(txDetails?: Truffle.TransactionDetails): Promise<string[]>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
