/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface ILendingPoolContract
  extends Truffle.Contract<ILendingPoolInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<ILendingPoolInstance>;
}

export interface Borrow {
  name: "Borrow";
  args: {
    _reserve: string;
    _user: string;
    _amount: BN;
    _borrowRateMode: BN;
    _borrowRate: BN;
    _originationFee: BN;
    _borrowBalanceIncrease: BN;
    _referral: BN;
    _timestamp: BN;
    0: string;
    1: string;
    2: BN;
    3: BN;
    4: BN;
    5: BN;
    6: BN;
    7: BN;
    8: BN;
  };
}

export interface Deposit {
  name: "Deposit";
  args: {
    _reserve: string;
    _user: string;
    _amount: BN;
    _referral: BN;
    _timestamp: BN;
    0: string;
    1: string;
    2: BN;
    3: BN;
    4: BN;
  };
}

export interface FlashLoan {
  name: "FlashLoan";
  args: {
    _target: string;
    _reserve: string;
    _amount: BN;
    _totalFee: BN;
    _protocolFee: BN;
    _timestamp: BN;
    0: string;
    1: string;
    2: BN;
    3: BN;
    4: BN;
    5: BN;
  };
}

export interface LiquidationCall {
  name: "LiquidationCall";
  args: {
    _collateral: string;
    _reserve: string;
    _user: string;
    _purchaseAmount: BN;
    _liquidatedCollateralAmount: BN;
    _accruedBorrowInterest: BN;
    _liquidator: string;
    _receiveAToken: boolean;
    _timestamp: BN;
    0: string;
    1: string;
    2: string;
    3: BN;
    4: BN;
    5: BN;
    6: string;
    7: boolean;
    8: BN;
  };
}

export interface OriginationFeeLiquidated {
  name: "OriginationFeeLiquidated";
  args: {
    _collateral: string;
    _reserve: string;
    _user: string;
    _feeLiquidated: BN;
    _liquidatedCollateralForFee: BN;
    _timestamp: BN;
    0: string;
    1: string;
    2: string;
    3: BN;
    4: BN;
    5: BN;
  };
}

export interface RebalanceStableBorrowRate {
  name: "RebalanceStableBorrowRate";
  args: {
    _reserve: string;
    _user: string;
    _newStableRate: BN;
    _borrowBalanceIncrease: BN;
    _timestamp: BN;
    0: string;
    1: string;
    2: BN;
    3: BN;
    4: BN;
  };
}

export interface RedeemUnderlying {
  name: "RedeemUnderlying";
  args: {
    _reserve: string;
    _user: string;
    _amount: BN;
    _timestamp: BN;
    0: string;
    1: string;
    2: BN;
    3: BN;
  };
}

export interface Repay {
  name: "Repay";
  args: {
    _reserve: string;
    _user: string;
    _repayer: string;
    _amountMinusFees: BN;
    _fees: BN;
    _borrowBalanceIncrease: BN;
    _timestamp: BN;
    0: string;
    1: string;
    2: string;
    3: BN;
    4: BN;
    5: BN;
    6: BN;
  };
}

export interface ReserveUsedAsCollateralDisabled {
  name: "ReserveUsedAsCollateralDisabled";
  args: {
    _reserve: string;
    _user: string;
    0: string;
    1: string;
  };
}

export interface ReserveUsedAsCollateralEnabled {
  name: "ReserveUsedAsCollateralEnabled";
  args: {
    _reserve: string;
    _user: string;
    0: string;
    1: string;
  };
}

export interface Swap {
  name: "Swap";
  args: {
    _reserve: string;
    _user: string;
    _newRateMode: BN;
    _newRate: BN;
    _borrowBalanceIncrease: BN;
    _timestamp: BN;
    0: string;
    1: string;
    2: BN;
    3: BN;
    4: BN;
    5: BN;
  };
}

type AllEvents =
  | Borrow
  | Deposit
  | FlashLoan
  | LiquidationCall
  | OriginationFeeLiquidated
  | RebalanceStableBorrowRate
  | RedeemUnderlying
  | Repay
  | ReserveUsedAsCollateralDisabled
  | ReserveUsedAsCollateralEnabled
  | Swap;

export interface ILendingPoolInstance extends Truffle.ContractInstance {
  /**
   * deposits The underlying asset into the reserve. A corresponding amount of the overlying asset (aTokens) is minted.
   * @param _amount the amount to be deposited
   * @param _referralCode integrators are assigned a referral code and can potentially receive rewards.*
   * @param _reserve the address of the reserve
   */
  deposit: {
    (
      _reserve: string,
      _amount: number | BN | string,
      _referralCode: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _reserve: string,
      _amount: number | BN | string,
      _referralCode: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _reserve: string,
      _amount: number | BN | string,
      _referralCode: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _reserve: string,
      _amount: number | BN | string,
      _referralCode: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Redeems the underlying amount of assets requested by _user. This function is executed by the overlying aToken contract in response to a redeem action.
   * @param _amount the underlying amount to be redeemed*
   * @param _reserve the address of the reserve
   * @param _user the address of the user performing the action
   */
  redeemUnderlying: {
    (
      _reserve: string,
      _user: string,
      _amount: number | BN | string,
      _aTokenBalanceAfterRedeem: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _reserve: string,
      _user: string,
      _amount: number | BN | string,
      _aTokenBalanceAfterRedeem: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _reserve: string,
      _user: string,
      _amount: number | BN | string,
      _aTokenBalanceAfterRedeem: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _reserve: string,
      _user: string,
      _amount: number | BN | string,
      _aTokenBalanceAfterRedeem: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Allows users to borrow a specific amount of the reserve currency, provided that the borrower already deposited enough collateral.
   * @param _amount the amount to be borrowed
   * @param _interestRateMode the interest rate mode at which the user wants to borrow. Can be 0 (STABLE) or 1 (VARIABLE)*
   * @param _reserve the address of the reserve
   */
  borrow: {
    (
      _reserve: string,
      _amount: number | BN | string,
      _interestRateMode: number | BN | string,
      _referralCode: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _reserve: string,
      _amount: number | BN | string,
      _interestRateMode: number | BN | string,
      _referralCode: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _reserve: string,
      _amount: number | BN | string,
      _interestRateMode: number | BN | string,
      _referralCode: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _reserve: string,
      _amount: number | BN | string,
      _interestRateMode: number | BN | string,
      _referralCode: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  repay: {
    (
      _reserve: string,
      _amount: number | BN | string,
      _onBehalfOf: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _reserve: string,
      _amount: number | BN | string,
      _onBehalfOf: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _reserve: string,
      _amount: number | BN | string,
      _onBehalfOf: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _reserve: string,
      _amount: number | BN | string,
      _onBehalfOf: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * borrowers can user this function to swap between stable and variable borrow rate modes.
   * @param _reserve the address of the reserve on which the user borrowed*
   */
  swapBorrowRateMode: {
    (_reserve: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _reserve: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _reserve: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _reserve: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * rebalances the stable interest rate of a user if current liquidity rate > user stable rate. this is regulated by Aave to ensure that the protocol is not abused, and the user is paying a fair rate. Anyone can call this function though.
   * @param _reserve the address of the reserve
   * @param _user the address of the user to be rebalanced*
   */
  rebalanceStableBorrowRate: {
    (
      _reserve: string,
      _user: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _reserve: string,
      _user: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _reserve: string,
      _user: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _reserve: string,
      _user: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * allows depositors to enable or disable a specific deposit as collateral.
   * @param _reserve the address of the reserve
   * @param _useAsCollateral true if the user wants to user the deposit as collateral, false otherwise.*
   */
  setUserUseReserveAsCollateral: {
    (
      _reserve: string,
      _useAsCollateral: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _reserve: string,
      _useAsCollateral: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _reserve: string,
      _useAsCollateral: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _reserve: string,
      _useAsCollateral: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * users can invoke this function to liquidate an undercollateralized position.
   * @param _purchaseAmount the amount of principal that the liquidator wants to repay
   * @param _receiveAToken true if the liquidators wants to receive the aTokens, false if he wants to receive the underlying asset directly*
   * @param _reserve the address of the principal reserve
   * @param _user the address of the borrower
   */
  liquidationCall: {
    (
      _collateral: string,
      _reserve: string,
      _user: string,
      _purchaseAmount: number | BN | string,
      _receiveAToken: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _collateral: string,
      _reserve: string,
      _user: string,
      _purchaseAmount: number | BN | string,
      _receiveAToken: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _collateral: string,
      _reserve: string,
      _user: string,
      _purchaseAmount: number | BN | string,
      _receiveAToken: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _collateral: string,
      _reserve: string,
      _user: string,
      _purchaseAmount: number | BN | string,
      _receiveAToken: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * accessory functions to fetch data from the core contract*
   */
  getReserveConfigurationData(
    _reserve: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<[BN, BN, BN, string, boolean, boolean, boolean, boolean]>;

  getReserveData(
    _reserve: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<[BN, BN, BN, BN, BN, BN, BN, BN, BN, BN, BN, string, BN]>;

  getUserAccountData(
    _user: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<[BN, BN, BN, BN, BN, BN, BN, BN]>;

  getUserReserveData(
    _reserve: string,
    _user: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<[BN, BN, BN, BN, BN, BN, BN, BN, BN, boolean]>;

  getReserves(txDetails?: Truffle.TransactionDetails): Promise<string[]>;

  methods: {
    /**
     * deposits The underlying asset into the reserve. A corresponding amount of the overlying asset (aTokens) is minted.
     * @param _amount the amount to be deposited
     * @param _referralCode integrators are assigned a referral code and can potentially receive rewards.*
     * @param _reserve the address of the reserve
     */
    deposit: {
      (
        _reserve: string,
        _amount: number | BN | string,
        _referralCode: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _reserve: string,
        _amount: number | BN | string,
        _referralCode: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _reserve: string,
        _amount: number | BN | string,
        _referralCode: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _reserve: string,
        _amount: number | BN | string,
        _referralCode: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Redeems the underlying amount of assets requested by _user. This function is executed by the overlying aToken contract in response to a redeem action.
     * @param _amount the underlying amount to be redeemed*
     * @param _reserve the address of the reserve
     * @param _user the address of the user performing the action
     */
    redeemUnderlying: {
      (
        _reserve: string,
        _user: string,
        _amount: number | BN | string,
        _aTokenBalanceAfterRedeem: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _reserve: string,
        _user: string,
        _amount: number | BN | string,
        _aTokenBalanceAfterRedeem: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _reserve: string,
        _user: string,
        _amount: number | BN | string,
        _aTokenBalanceAfterRedeem: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _reserve: string,
        _user: string,
        _amount: number | BN | string,
        _aTokenBalanceAfterRedeem: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Allows users to borrow a specific amount of the reserve currency, provided that the borrower already deposited enough collateral.
     * @param _amount the amount to be borrowed
     * @param _interestRateMode the interest rate mode at which the user wants to borrow. Can be 0 (STABLE) or 1 (VARIABLE)*
     * @param _reserve the address of the reserve
     */
    borrow: {
      (
        _reserve: string,
        _amount: number | BN | string,
        _interestRateMode: number | BN | string,
        _referralCode: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _reserve: string,
        _amount: number | BN | string,
        _interestRateMode: number | BN | string,
        _referralCode: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _reserve: string,
        _amount: number | BN | string,
        _interestRateMode: number | BN | string,
        _referralCode: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _reserve: string,
        _amount: number | BN | string,
        _interestRateMode: number | BN | string,
        _referralCode: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    repay: {
      (
        _reserve: string,
        _amount: number | BN | string,
        _onBehalfOf: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _reserve: string,
        _amount: number | BN | string,
        _onBehalfOf: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _reserve: string,
        _amount: number | BN | string,
        _onBehalfOf: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _reserve: string,
        _amount: number | BN | string,
        _onBehalfOf: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * borrowers can user this function to swap between stable and variable borrow rate modes.
     * @param _reserve the address of the reserve on which the user borrowed*
     */
    swapBorrowRateMode: {
      (_reserve: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _reserve: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _reserve: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _reserve: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * rebalances the stable interest rate of a user if current liquidity rate > user stable rate. this is regulated by Aave to ensure that the protocol is not abused, and the user is paying a fair rate. Anyone can call this function though.
     * @param _reserve the address of the reserve
     * @param _user the address of the user to be rebalanced*
     */
    rebalanceStableBorrowRate: {
      (
        _reserve: string,
        _user: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _reserve: string,
        _user: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _reserve: string,
        _user: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _reserve: string,
        _user: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * allows depositors to enable or disable a specific deposit as collateral.
     * @param _reserve the address of the reserve
     * @param _useAsCollateral true if the user wants to user the deposit as collateral, false otherwise.*
     */
    setUserUseReserveAsCollateral: {
      (
        _reserve: string,
        _useAsCollateral: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _reserve: string,
        _useAsCollateral: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _reserve: string,
        _useAsCollateral: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _reserve: string,
        _useAsCollateral: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * users can invoke this function to liquidate an undercollateralized position.
     * @param _purchaseAmount the amount of principal that the liquidator wants to repay
     * @param _receiveAToken true if the liquidators wants to receive the aTokens, false if he wants to receive the underlying asset directly*
     * @param _reserve the address of the principal reserve
     * @param _user the address of the borrower
     */
    liquidationCall: {
      (
        _collateral: string,
        _reserve: string,
        _user: string,
        _purchaseAmount: number | BN | string,
        _receiveAToken: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _collateral: string,
        _reserve: string,
        _user: string,
        _purchaseAmount: number | BN | string,
        _receiveAToken: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _collateral: string,
        _reserve: string,
        _user: string,
        _purchaseAmount: number | BN | string,
        _receiveAToken: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _collateral: string,
        _reserve: string,
        _user: string,
        _purchaseAmount: number | BN | string,
        _receiveAToken: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * accessory functions to fetch data from the core contract*
     */
    getReserveConfigurationData(
      _reserve: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<[BN, BN, BN, string, boolean, boolean, boolean, boolean]>;

    getReserveData(
      _reserve: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<[BN, BN, BN, BN, BN, BN, BN, BN, BN, BN, BN, string, BN]>;

    getUserAccountData(
      _user: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<[BN, BN, BN, BN, BN, BN, BN, BN]>;

    getUserReserveData(
      _reserve: string,
      _user: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<[BN, BN, BN, BN, BN, BN, BN, BN, BN, boolean]>;

    getReserves(txDetails?: Truffle.TransactionDetails): Promise<string[]>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
