/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { AaveLendingPoolMockContract } from "./AaveLendingPoolMock";
import { AaveProviderContract } from "./AaveProvider";
import { AbstractProviderContract } from "./AbstractProvider";
import { AddressRepositoryContract } from "./AddressRepository";
import { AddressStorageContract } from "./AddressStorage";
import { ATokenContract } from "./AToken";
import { DaiMockTokenContract } from "./DaiMockToken";
import { Erc20Contract } from "./Erc20";
import { IAaveLendingPoolContract } from "./IAaveLendingPool";
import { Ierc20Contract } from "./Ierc20";
import { ILendingPoolCoreContract } from "./ILendingPoolCore";
import { ILendingProviderContract } from "./ILendingProvider";
import { MigrationsContract } from "./Migrations";
import { OwnableContract } from "./Ownable";
import { PoolServiceContract } from "./PoolService";
import { PriceRepositoryContract } from "./PriceRepository";
import { ProviderRepositoryContract } from "./ProviderRepository";
import { ProviderServiceContract } from "./ProviderService";
import { RateServiceContract } from "./RateService";
import { ReserveRepositoryContract } from "./ReserveRepository";
import { UserBalanceRepositoryContract } from "./UserBalanceRepository";
import { VTokenContract } from "./VToken";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AaveLendingPoolMock"): AaveLendingPoolMockContract;
      require(name: "AaveProvider"): AaveProviderContract;
      require(name: "AbstractProvider"): AbstractProviderContract;
      require(name: "AddressRepository"): AddressRepositoryContract;
      require(name: "AddressStorage"): AddressStorageContract;
      require(name: "AToken"): ATokenContract;
      require(name: "DAIMockToken"): DaiMockTokenContract;
      require(name: "ERC20"): Erc20Contract;
      require(name: "IAaveLendingPool"): IAaveLendingPoolContract;
      require(name: "IERC20"): Ierc20Contract;
      require(name: "ILendingPoolCore"): ILendingPoolCoreContract;
      require(name: "ILendingProvider"): ILendingProviderContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "PoolService"): PoolServiceContract;
      require(name: "PriceRepository"): PriceRepositoryContract;
      require(name: "ProviderRepository"): ProviderRepositoryContract;
      require(name: "ProviderService"): ProviderServiceContract;
      require(name: "RateService"): RateServiceContract;
      require(name: "ReserveRepository"): ReserveRepositoryContract;
      require(name: "UserBalanceRepository"): UserBalanceRepositoryContract;
      require(name: "VToken"): VTokenContract;
    }
  }
}

export {
  AaveLendingPoolMockContract,
  AaveLendingPoolMockInstance
} from "./AaveLendingPoolMock";
export { AaveProviderContract, AaveProviderInstance } from "./AaveProvider";
export {
  AbstractProviderContract,
  AbstractProviderInstance
} from "./AbstractProvider";
export {
  AddressRepositoryContract,
  AddressRepositoryInstance
} from "./AddressRepository";
export {
  AddressStorageContract,
  AddressStorageInstance
} from "./AddressStorage";
export { ATokenContract, ATokenInstance } from "./AToken";
export { DaiMockTokenContract, DaiMockTokenInstance } from "./DaiMockToken";
export { Erc20Contract, Erc20Instance } from "./Erc20";
export {
  IAaveLendingPoolContract,
  IAaveLendingPoolInstance
} from "./IAaveLendingPool";
export { Ierc20Contract, Ierc20Instance } from "./Ierc20";
export {
  ILendingPoolCoreContract,
  ILendingPoolCoreInstance
} from "./ILendingPoolCore";
export {
  ILendingProviderContract,
  ILendingProviderInstance
} from "./ILendingProvider";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { OwnableContract, OwnableInstance } from "./Ownable";
export { PoolServiceContract, PoolServiceInstance } from "./PoolService";
export {
  PriceRepositoryContract,
  PriceRepositoryInstance
} from "./PriceRepository";
export {
  ProviderRepositoryContract,
  ProviderRepositoryInstance
} from "./ProviderRepository";
export {
  ProviderServiceContract,
  ProviderServiceInstance
} from "./ProviderService";
export { RateServiceContract, RateServiceInstance } from "./RateService";
export {
  ReserveRepositoryContract,
  ReserveRepositoryInstance
} from "./ReserveRepository";
export {
  UserBalanceRepositoryContract,
  UserBalanceRepositoryInstance
} from "./UserBalanceRepository";
export { VTokenContract, VTokenInstance } from "./VToken";
