/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { AddressStorageContract } from "./AddressStorage";
import { MigrationsContract } from "./Migrations";
import { PoolContract } from "./Pool";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AddressStorage"): AddressStorageContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "Pool"): PoolContract;
    }
  }
}

export {
  AddressStorageContract,
  AddressStorageInstance
} from "./AddressStorage";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { PoolContract, PoolInstance } from "./Pool";
