/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface RateServiceContract
  extends Truffle.Contract<RateServiceInstance> {
  "new"(
    _addressRepository: string,
    meta?: Truffle.TransactionDetails
  ): Promise<RateServiceInstance>;
}

type AllEvents = never;

export interface RateServiceInstance extends Truffle.ContractInstance {
  getDepositRate(
    _reserve: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  getBorrowRate(
    _reserve: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  computeBestBorrowRate(
    _bestDepositRate: number | BN | string,
    _bestBorrowRate: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  methods: {
    getDepositRate(
      _reserve: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    getBorrowRate(
      _reserve: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    computeBestBorrowRate(
      _bestDepositRate: number | BN | string,
      _bestBorrowRate: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
